name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn
      - run: npx @vercel/ncc build ./.github/workflows/lib/main.ts -o ./.github/workflows/dist
        env:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn test:ci
      - run: node ./.github/workflows/dist
      - uses: amondnet/vercel-action@v20.0.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./coverage/lcov-report
